### ISSUE TITLE
write() seeks offset twice

### ISSUE THREAD

**Issue by dsd** [kylemanna/pydevmem#6]
If I try to work with address 0x40, due to page alignment we end up mmapping the data starting at 0x0 and then `base_addr_offset` is calculated to be 0x40.

Reading seems to be working OK, but I think there is a bug in the write path. The 0x40 offset is accounted for twice and the seek ends up going to the wrong place.

The code flow is:
```
        # Compensate for the base_address not being what the user requested
        offset += self.base_addr_offset
```

So `offset` has now accounted for this.

Then:
```
        # Seek to the aligned offset
        virt_base_addr = self.base_addr_offset & self.mask
```

So `virt_base_addr` has also accounted for this.

Then:
```
        mem.seek(virt_base_addr + offset)
```

Both are added together, we have accounted for the 0x40 offset twice...

**Comment by kylemanna** [comment]
Should be resolved by #3
